#!/bin/sh

# This file is a plugin of netfilter-persistent package.
# Copyright (C) 2019, Đặng Minh Dũng <dungdm93@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.

set -e

rc=0

load_rules()
{
    if [ ! -f /etc/ipvs/rules ]; then
        echo "Warning: skipping IPVS (no rules to load)"
    else
        flush_rules
        /sbin/ipvsadm --restore < /etc/ipvs/rules 2> /dev/null
        if [ $? -ne 0 ]; then
            rc=1
        fi
    fi
}

save_rules()
{
    if [ -x /sbin/ipvsadm ]; then
        touch /etc/ipvs/rules
        chmod 0640 /etc/ipvs/rules
        /sbin/ipvsadm --save --numeric > /etc/ipvs/rules
        if [ $? -ne 0 ]; then
            rc=1
        fi
    fi
}

flush_rules()
{
    if [ -x /sbin/ipvsadm ]; then
        /sbin/ipvsadm --clear
    fi
}

case "$1" in
start|restart|reload|force-reload)
    load_rules
    ;;
save)
    save_rules
    ;;
stop)
    # Why? because if stop is used, the ipvs gets flushed for a variable
    # amount of time during package upgrades, leaving the services downtime.
    # It's also not always desirable to flush during purge
    echo "Automatic flushing disabled, use \"flush\" instead of \"stop\""
    ;;
flush)
    flush_rules
    ;;
*)
    echo "Usage: $0 {start|restart|reload|force-reload|save|flush}" >&2
    exit 1
    ;;
esac

exit $rc
